### ISSUE TITLE
ModuleNotFoundError: No module named 'py'

### ISSUE THREAD

**Issue by ftherrien** [pylada/pylada-light#55]
When I install pylada in an empy envrionment I get the following error:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/felixt/.conda-envs/testcw/lib/python3.8/site-packages/pylada/__init__.py", line 121, in <module>
    logger = __setup_logger()
  File "/home/felixt/.conda-envs/testcw/lib/python3.8/site-packages/pylada/__init__.py", line 100, in __setup_logger
    local_dict = __exec_config_files("logging.py")
  File "/home/felixt/.conda-envs/testcw/lib/python3.8/site-packages/pylada/__init__.py", line 87, in __exec_config_files
    for filename in __find_config_files(pattern, rcfile):
  File "/home/felixt/.conda-envs/testcw/lib/python3.8/site-packages/pylada/__init__.py", line 68, in __find_config_files
    from py.path import local
ModuleNotFoundError: No module named 'py'

```

This is a new error because "py" used to be installed as a dependency for "pytest" but it seems like it is no longer installed since pytest is required only for tests (`tests_require`).

We could maybe add "py" to `install_requires` or not use `py.path` whatsoever and use "os" instead? @mdavezac, what do you think?

**Comment by mdavezac** [comment]
IMHO, if we were to remove py.path, we would probably want to replace it with pathlib from the standard library https://docs.python.org/3/library/pathlib.html
