### ISSUE TITLE
primitive leads to: pylada.error.RuntimeError: Size and volumes do not match.

### ISSUE THREAD

**Issue by ftherrien** [pylada/pylada-light#65]
Using the primitive functions when the structure is not primitive leads to the error stated in the title. For example:

With the following structure (`POSCAR_Si`)

```
cubic diamond
   5.43
 1.0    0.0     0.0
 0.0    1.0     0.0
 0.0    0.0     1.0
 Si
 8
Direct
 -0.125 -0.125 -0.125
 -0.125  0.375  0.375
  0.375 -0.125  0.375
  0.375  0.375 -0.125
  0.125  0.125  0.125
  0.125  0.625  0.625
  0.625  0.125  0.625
  0.625  0.625  0.125
```
I run:

`python -c "from pylada.crystal import read, primitive; primitive(read.poscar(\"POSCAR_Si\"))"`

and I get:

```
03/15/2023 11:49:08 PM Size and volumes do not match.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "_primitive.pyx", line 152, in pylada.crystal._primitive.primitive
pylada.error.RuntimeError: Size and volumes do not match.
```

This was not the case for a version of pylada installed in Jan 2022.

**Comment by ftherrien** [comment]
The problem is that the cython language level is set to python 2 instead of python 3. This results in an integer division being returned as an int instead of a float.

The cython language level is set here: https://github.com/pylada/pylada-light/blob/f1feb140160bb8b7ccfb31c2a3bb7bfa0f4a77d9/src/pylada/crystal/CMakeLists.txt#L32

*There is an extra curly brace after PYVER*. Seems like in scikit-build 0.12.0 this does not result in any issue and the language level is set to 3 despite the typo. In newer version of scikit-build, the typo *does* have an impact and the language level is set to 2 which leads to this new error.
